FROM public.ecr.aws/lambda/python:3.12

# renovate: datasource=github-releases depName=hashicorp/terraform extractVersion=^v(?<version>.*)$
ARG TERRAFORM_VERSION=1.9.5

ARG CDKTF_VERSION=0.20.5

# renovate: datasource=terraform-provider registryUrl=https://tf.app.wiz.io depName=wiz packageName=wizsec/wiz extractVersion=^(?<version>.*)
ARG WIZ_TERRAFORM_PROVIDER_VERSION=1.15.4253
